#!/usr/bin/env python3
"""Generate TypeSpec model files under models-auto/ from
.spec/draft-ietf-rpp-data-objects.yaml.

See PLAN-GENERATOR.md at the repo root for the full design/rationale.
Re-run after the YAML changes: .venv/bin/python3 tools/generate_models.py
"""

import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_YAML = REPO_ROOT / ".spec" / "draft-ietf-rpp-data-objects.yaml"
OUT_DIR = REPO_ROOT / "models-auto"

HEADER = (
    "// AUTO-GENERATED by tools/generate_models.py from "
    ".spec/draft-ietf-rpp-data-objects.yaml — do not hand-edit.\n\n"
)

# ---------------------------------------------------------------------------
# Warning collection (no-silent-inference principle)
# ---------------------------------------------------------------------------

_warnings = []


def warn(message):
    _warnings.append(message)
    print(f"WARNING: {message}", file=sys.stderr)


def warn_summary():
    print(f"\n{len(_warnings)} warning(s) emitted during generation.", file=sys.stderr)


# ---------------------------------------------------------------------------
# File writer
# ---------------------------------------------------------------------------

_written_files = []


def write_tsp(relative_path, body):
    """Write one .tsp file (one model per file), tracking it for main.tsp."""
    full_path = OUT_DIR / relative_path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    full_path.write_text(HEADER + body.rstrip() + "\n")
    _written_files.append(relative_path)


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------


def kebab(identifier):
    """camelCase identifier -> kebab-case for folder/file names."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", identifier)
    return s.lower()


def pascal(identifier):
    return identifier[0].upper() + identifier[1:] if identifier else identifier


# ---------------------------------------------------------------------------
# Cardinality mapping
# ---------------------------------------------------------------------------


def apply_cardinality(cardinality, ts_type):
    if cardinality == "1":
        return ts_type
    if cardinality == "0-1":
        return ts_type, True  # handled specially below (optional marker)
    return ts_type


def field_type_and_optional(cardinality, ts_type):
    """Return (typespec_type_expr, optional: bool) for a field."""
    if cardinality == "1":
        return ts_type, False
    if cardinality == "0-1":
        return ts_type, True
    if cardinality == "0+":
        return f"{ts_type}[]", True
    if cardinality == "1+":
        return f"{ts_type}[]", False
    if cardinality == "1-2":
        return f"{ts_type}[]", False
    warn(f'unrecognized cardinality "{cardinality}" — defaulting to optional array')
    return f"{ts_type}[]", True


def visibility_decorator(mutability):
    if mutability == "read-only":
        return "@visibility(Lifecycle.Read, Lifecycle.Query) "
    if mutability == "create-only":
        return "@visibility(Lifecycle.Create, Lifecycle.Read, Lifecycle.Query) "
    if mutability == "read-write":
        return ""
    if mutability is None:
        return ""
    warn(f'unrecognized mutability "{mutability}" — no visibility decorator applied')
    return ""


# ---------------------------------------------------------------------------
# Object graph indices (built from the YAML)
# ---------------------------------------------------------------------------

class ObjectGraph:
    def __init__(self, doc):
        self.components = doc.get("components", [])
        self.processes = doc.get("processes", [])
        self.resources = doc.get("resources", [])

        self.by_identifier = {}
        self.by_name = {}
        for kind, items in (
            ("component", self.components),
            ("process", self.processes),
            ("resource", self.resources),
        ):
            for obj in items:
                obj["_kind"] = kind
                self.by_identifier[obj["identifier"]] = obj
                self.by_name[obj["name"]] = obj

    def namespace_for(self, identifier):
        """rpp.gen namespace path for a given object identifier."""
        return f"rpp.gen.{identifier}"

    def model_ref_for(self, identifier):
        """Type reference to the bare/full object model for a given identifier.

        Components are emitted as `model <identifier>` directly in `rpp.gen`.
        Processes/resources are emitted as `model Model` nested inside
        `namespace rpp.gen.<identifier>` (alongside `reference` and per-operation
        namespaces), since TypeSpec forbids a model and namespace sharing a name.
        """
        obj = self.by_identifier.get(identifier)
        if obj is not None and obj["_kind"] == "component":
            return f"rpp.gen.{identifier}"
        return f"rpp.gen.{identifier}.Model"


UNIQUE_ID_TABLE = {
    "transferProcess": "processId",
    "restoreProcess": "processId",
    "renewProcess": "processId",
    "createProcess": "processId",
    "domainCreateProcess": "processId",
    "domainName": "name",
    "contact": "id",
    "host": "hostName",
    "organisation": "id",
    "user": "id",
}


# ---------------------------------------------------------------------------
# Name resolution (data_type free text -> known object)
# ---------------------------------------------------------------------------


def strip_trailing_dot(s):
    if s.endswith("."):
        return s[:-1]
    return s


def resolve_object_name(raw_name, graph, context=""):
    """Resolve a free-text object-name string to a graph object.

    Returns the object dict, or None if unresolved (caller emits `unknown`).
    """
    name = strip_trailing_dot(raw_name.strip())

    if name in graph.by_name:
        return graph.by_name[name]

    # fuzzy match: strip " Data Object" / " Object" suffix, compare against identifiers
    stripped = re.sub(r"\s+Data Object$", "", name)
    stripped = re.sub(r"\s+Object$", "", stripped)
    candidate_identifier = stripped[0].lower() + stripped[1:].replace(" ", "") if stripped else ""

    for obj in graph.by_identifier.values():
        if obj["identifier"].lower() == candidate_identifier.lower():
            warn(
                f'fuzzy-matched data_type "{raw_name}"{context} to object '
                f'"{obj["identifier"]}" (name "{obj["name"]}") via suffix-stripping'
            )
            return obj

    # try matching against name with suffixes stripped too
    for obj in graph.by_identifier.values():
        obj_name_stripped = re.sub(r"\s+Data Object$", "", obj["name"])
        obj_name_stripped = re.sub(r"\s+Object$", "", obj_name_stripped)
        if obj_name_stripped.strip().lower() == stripped.strip().lower():
            warn(
                f'fuzzy-matched data_type "{raw_name}"{context} to object '
                f'"{obj["identifier"]}" (name "{obj["name"]}") via suffix-stripping'
            )
            return obj

    return None


# ---------------------------------------------------------------------------
# data_type -> TypeSpec type expression
# ---------------------------------------------------------------------------

PRIMITIVE_MAP = {
    "String": "string",
    "Integer": "int32",
    "Boolean": "boolean",
    "Decimal": "decimal",
    "Date": "plainDate",
    "Timestamp": "utcDateTime",
    "URL": "url",
    "Binary": "bytes",
}

_external_types_seen = {}  # (spec, type) -> pascal identifier


def external_type_name(spec, type_name):
    key = (spec, type_name)
    if key not in _external_types_seen:
        ident = "".join(p.capitalize() for p in re.split(r"[-_]", spec)) + type_name
        _external_types_seen[key] = ident
    return _external_types_seen[key]


ASSOCIATION_WRAPPERS = {
    "Aggregation": ("Aggregation", True),
    "Composition": ("Composition", False),
    "LabelledAggregation": ("LabelledAggregation", True),
    "DictionaryAggregation": ("DictionaryAggregation", True),
    "LabelledComposition": ("LabelledComposition", False),
    "DictionaryComposition": ("DictionaryComposition", False),
}


def resolve_data_type(raw_data_type, graph, context=""):
    """Return a TypeSpec type expression string for a YAML data_type value."""
    dt = raw_data_type.strip()

    # Association wrappers: Aggregation[X], Composition[X], etc.
    m = re.match(r"^(Aggregation|Composition|LabelledAggregation|DictionaryAggregation|"
                 r"LabelledComposition|DictionaryComposition)\[(.+)\]$", dt)
    if m:
        wrapper, inner = m.group(1), m.group(2)
        ts_wrapper, targets_reference = ASSOCIATION_WRAPPERS[wrapper]
        inner_type = resolve_data_type(inner, graph, context=f" (inside {wrapper}[...])")
        if targets_reference:
            inner_obj = resolve_object_name(inner, graph, context=f" (inside {wrapper}[...])")
            if inner_obj is not None and inner_obj["_kind"] in ("process", "resource"):
                inner_type = f"{graph.namespace_for(inner_obj['identifier'])}.reference"
        return f"{ts_wrapper}<{inner_type}>"

    # Dictionary[X]
    m = re.match(r"^Dictionary\[(.+)\]$", dt)
    if m:
        inner_type = resolve_data_type(m.group(1), graph, context=" (inside Dictionary[...])")
        return f"Record<{inner_type}>"

    # External:<spec>:<type>
    m = re.match(r"^External:([^:]+):(.+)$", dt)
    if m:
        spec, type_name = m.group(1), m.group(2)
        ident = external_type_name(spec, type_name)
        return f"rpp.gen.external.{ident}"

    # "<Name> Reference" — must check before generic name resolution
    m = re.match(r"^(.*)\s+Reference$", dt)
    if m:
        base_name = m.group(1)
        warn(
            f'data_type "{dt}"{context} ends in "Reference" — treating as reference-to '
            f'"{base_name}", resolving to its .reference model'
        )
        target = resolve_object_name(base_name, graph, context=context)
        if target is not None and target["_kind"] in ("process", "resource"):
            return f"{graph.namespace_for(target['identifier'])}.reference"
        if target is not None:
            warn(
                f'data_type "{dt}"{context} resolved to component "{target["identifier"]}" '
                f'which has no .reference model — using its plain model instead'
            )
            return graph.model_ref_for(target["identifier"])
        warn(f'unresolved "Reference" data_type "{dt}"{context}')
        return "unknown"

    # Identifier / Identifier. (trailing dot)
    if strip_trailing_dot(dt) == "Identifier":
        if dt.endswith("."):
            warn(f'data_type "{dt}"{context} has a trailing-dot typo — stripped to "Identifier"')
        return "rpp.gen.common.Identifier"

    if dt == "Client Identifier":
        return "rpp.gen.common.ClientIdentifier"

    if dt == "Phone Number":
        return "rpp.gen.common.PhoneNumber"

    if dt == "Object":
        return "Record<unknown>"

    if dt in PRIMITIVE_MAP:
        return PRIMITIVE_MAP[dt]

    # Plain object-name reference: "<Name> Object", "<Name> Data Object", or a bare object name
    obj = resolve_object_name(dt, graph, context=context)
    if obj is not None:
        return graph.model_ref_for(obj["identifier"])

    warn(f'unresolved data_type "{dt}"{context} — emitting `unknown`')
    return "unknown"


def data_type_comment(raw_data_type, resolved):
    if resolved == "unknown":
        return f'  // TODO: unresolved data_type "{raw_data_type}"\n'
    return ""


# ---------------------------------------------------------------------------
# Field emission (shared by elements and params)
# ---------------------------------------------------------------------------


def emit_field(identifier, cardinality, data_type, mutability, graph, context=""):
    """Return one field declaration (plus optional TODO comment line), unindented.

    Callers splice this into a model body via `indent_block`, which applies the
    indent appropriate to that body's nesting depth.
    """
    ts_type = resolve_data_type(data_type, graph, context=context)
    type_expr, optional = field_type_and_optional(cardinality, ts_type)
    vis = visibility_decorator(mutability) if mutability is not None else ""
    opt_marker = "?" if optional else ""
    comment = data_type_comment(data_type, ts_type)
    return f"{comment}{vis}{identifier}{opt_marker}: {type_expr};\n"


def indent_block(text, level):
    """Indent every non-empty line of `text` by `level` two-space steps."""
    prefix = "  " * level
    return "".join(prefix + line if line.strip() else line for line in text.splitlines(keepends=True))


# ---------------------------------------------------------------------------
# Component emission
# ---------------------------------------------------------------------------


def emit_component(obj, graph):
    identifier = obj["identifier"]
    fields = "".join(
        emit_field(
            el["identifier"], el["cardinality"], el["data_type"], el["mutability"], graph,
            context=f' (element "{el["identifier"]}" of component "{identifier}")',
        )
        for el in obj["elements"]
    )
    body = (
        f"namespace rpp.gen {{\n"
        f"  model {identifier} {{\n"
        f"{indent_block(fields, 2)}"
        f"  }}\n"
        f"}}\n"
    )
    write_tsp(f"components/{kebab(identifier)}.tsp", body)


# ---------------------------------------------------------------------------
# .reference model emission
# ---------------------------------------------------------------------------


def emit_reference(obj, graph):
    identifier = obj["identifier"]
    field_name = UNIQUE_ID_TABLE.get(identifier)
    elements_by_id = {el["identifier"]: el for el in obj["elements"]}

    if field_name is None:
        warn(
            f'object "{identifier}" has no entry in the hardcoded unique-identifier table — '
            f"falling back to its first element"
        )
        field_name = obj["elements"][0]["identifier"] if obj["elements"] else None

    if field_name is None or field_name not in elements_by_id:
        if field_name is not None:
            warn(
                f'unique-identifier table entry "{field_name}" for object "{identifier}" '
                f"not found among its elements — table is stale; falling back to first element"
            )
        field_name = obj["elements"][0]["identifier"] if obj["elements"] else None

    if field_name is None:
        warn(f'object "{identifier}" has no elements at all — emitting empty reference model')
        body = f"namespace rpp.gen {{\n  namespace {identifier} {{\n    model reference {{}}\n  }}\n}}\n"
        write_tsp(f"{_folder_for(obj)}/{kebab(identifier)}/reference.tsp", body)
        return

    el = elements_by_id[field_name]
    ts_type = resolve_data_type(
        el["data_type"], graph, context=f' (unique-id "{field_name}" of "{identifier}")'
    )

    body = (
        f"namespace rpp.gen {{\n"
        f"  namespace {identifier} {{\n"
        f"    model reference {{\n"
        f"      {field_name}: {ts_type};\n"
        f"    }}\n"
        f"  }}\n"
        f"}}\n"
    )
    write_tsp(f"{_folder_for(obj)}/{kebab(identifier)}/reference.tsp", body)


def _folder_for(obj):
    return "processes" if obj["_kind"] == "process" else "resources"


# ---------------------------------------------------------------------------
# Plain model.tsp emission for processes/resources (same shape as component,
# but placed under the nested namespace with the file name `model.tsp`)
# ---------------------------------------------------------------------------


def emit_object_model(obj, graph):
    identifier = obj["identifier"]
    fields = "".join(
        emit_field(
            el["identifier"], el["cardinality"], el["data_type"], el["mutability"], graph,
            context=f' (element "{el["identifier"]}" of "{identifier}")',
        )
        for el in obj["elements"]
    )
    body = (
        f"namespace rpp.gen {{\n"
        f"  namespace {identifier} {{\n"
        f"    model Model {{\n"
        f"{indent_block(fields, 3)}"
        f"    }}\n"
        f"  }}\n"
        f"}}\n"
    )
    write_tsp(f"{_folder_for(obj)}/{kebab(identifier)}/model.tsp", body)


# ---------------------------------------------------------------------------
# Operation input/output emission
# ---------------------------------------------------------------------------

CREATE_LIKE_OPS = {"create", "renewCreate", "transferCreate"}


def owning_object_full_field_defs(obj, graph, only_mutabilities, exclude_identifiers=frozenset()):
    """Emit fields for the elements of obj matching the given mutabilities."""
    parts = []
    for el in obj["elements"]:
        if el["mutability"] in only_mutabilities and el["identifier"] not in exclude_identifiers:
            parts.append(
                emit_field(
                    el["identifier"], el["cardinality"], el["data_type"], el["mutability"], graph,
                    context=f' (element "{el["identifier"]}" of "{obj["identifier"]}", '
                            f'operation-default input)',
                )
            )
    return "".join(parts)


def params_field_defs(op, graph, obj_identifier, op_identifier):
    parts = []
    for p in op.get("params", []):
        parts.append(
            emit_field(
                p["identifier"], p["cardinality"], p["data_type"], None, graph,
                context=f' (transient param "{p["identifier"]}" of '
                        f'"{obj_identifier}.{op_identifier}")',
            )
        )
    return "".join(parts)


def resolve_operation_input_fields(obj, op, graph):
    """Return the field-block string (without params) for the operation's input,
    applying §2.6.2 defaults / magic-value parsing per the plan's table."""
    raw_input = op.get("input", "") or ""
    op_id = op["identifier"]
    obj_id = obj["identifier"]

    if raw_input == "":
        if op_id in CREATE_LIKE_OPS:
            warn(f'applied Create default for empty input on "{obj_id}.{op_id}"')
            return owning_object_full_field_defs(obj, graph, {"create-only", "read-write"})
        if op_id == "read":
            warn(f'applied Read default for empty input on "{obj_id}.{op_id}" — reusing .reference')
            return f"...{graph.namespace_for(obj_id)}.reference;\n"
        if op_id == "update":
            warn(f'applied Update default for empty input on "{obj_id}.{op_id}"')
            id_field = f"...{graph.namespace_for(obj_id)}.reference;\n"
            unique_id_field = UNIQUE_ID_TABLE.get(obj_id)
            elements_by_id = {el["identifier"]: el for el in obj["elements"]}
            collides = (
                unique_id_field is not None
                and elements_by_id.get(unique_id_field, {}).get("mutability") == "read-write"
            )
            if collides:
                warn(
                    f'excluded unique-id field "{unique_id_field}" from the read-write spread on '
                    f'"{obj_id}.{op_id}" to avoid duplicating it with the .reference spread '
                    f"(it happens to also be mutability read-write on this object)"
                )
            return id_field + owning_object_full_field_defs(
                obj, graph, {"read-write"},
                exclude_identifiers={unique_id_field} if collides else frozenset(),
            )
        if op_id == "delete":
            warn(f'applied Delete default for empty input on "{obj_id}.{op_id}" — reusing .reference')
            return f"...{graph.namespace_for(obj_id)}.reference;\n"
        warn(
            f'empty input string on "{obj_id}.{op_id}" (identifier not in the known '
            f"create/read/update/delete default set) — emitting empty model"
        )
        return ""

    if raw_input.strip() == "None":
        warn(f'input "None" on "{obj_id}.{op_id}" — explicitly no input, empty model')
        return ""

    # "Object Identifier" / "Object Identifier, X"
    m = re.match(r"^Object Identifier\s*(?:,\s*(.+))?$", raw_input.strip())
    if m:
        warn(f'input "{raw_input}" on "{obj_id}.{op_id}" — modelled as .reference plus extra spread')
        extra = m.group(1)
        result = f"...{graph.namespace_for(obj_id)}.reference;\n"
        if extra:
            extra_obj = resolve_object_name(
                extra, graph, context=f' (input of "{obj_id}.{op_id}")'
            )
            if extra_obj is not None:
                result += f"...{graph.model_ref_for(extra_obj['identifier'])};\n"
            else:
                warn(f'unresolved extra input object "{extra}" on "{obj_id}.{op_id}"')
                result += f'// TODO: unparsed input/output string "{extra}"\n'
        return result

    # "<Name> Object (create-only and read-write elements)" pattern
    m = re.match(r"^(.+?)\s*\(create-only and read-write elements\)$", raw_input.strip())
    if m:
        target_name = m.group(1)
        warn(
            f'input "{raw_input}" on "{obj_id}.{op_id}" — resolved via name resolution to '
            f'"{target_name}", using its create-only+read-write fields'
        )
        target = resolve_object_name(target_name, graph, context=f' (input of "{obj_id}.{op_id}")')
        if target is not None:
            return owning_object_full_field_defs(target, graph, {"create-only", "read-write"})
        warn(f'unresolved input target "{target_name}" on "{obj_id}.{op_id}"')
        return f'// TODO: unparsed input/output string "{raw_input}"\n'

    # Exact object name
    target = resolve_object_name(raw_input.strip(), graph, context=f' (input of "{obj_id}.{op_id}")')
    if target is not None:
        warn(f'input "{raw_input}" on "{obj_id}.{op_id}" — resolved via name resolution')
        return f"...{graph.model_ref_for(target['identifier'])};\n"

    warn(f'unparsed input string "{raw_input}" on "{obj_id}.{op_id}"')
    return f'// TODO: unparsed input/output string "{raw_input}"\n'


def resolve_operation_output(obj, op, graph):
    """Return (is_distinct, type_expr_or_None, field_block_or_None).

    is_distinct False means: reuse the bare object model directly (no output.tsp).
    """
    raw_output = op.get("output", "") or ""
    op_id = op["identifier"]
    obj_id = obj["identifier"]

    if raw_output == "":
        warn(f'applied full-object default for empty output on "{obj_id}.{op_id}"')
        return False, None, None

    if raw_output.strip() == "None":
        warn(f'output "None" on "{obj_id}.{op_id}" — explicitly no output, empty model')
        return True, None, ""

    # "X or nothing"
    m = re.match(r"^(.+?)\s+or nothing$", raw_output.strip())
    if m:
        target_name = m.group(1)
        warn(
            f'output "{raw_output}" on "{obj_id}.{op_id}" — modelled as `{target_name} | void` '
            f"(TODO: confirm void/no-body convention)"
        )
        target = resolve_object_name(target_name, graph, context=f' (output of "{obj_id}.{op_id}")')
        type_ref = graph.model_ref_for(target["identifier"]) if target is not None else "unknown"
        if target is None:
            warn(f'unresolved output target "{target_name}" on "{obj_id}.{op_id}"')
        return True, f"{type_ref} | void", None

    # "<Name> Object (create-only and read-write elements)" — unlikely for output but handle
    target = resolve_object_name(raw_output.strip(), graph, context=f' (output of "{obj_id}.{op_id}")')
    if target is not None:
        if target["identifier"] == obj_id:
            warn(f'output "{raw_output}" on "{obj_id}.{op_id}" — resolves to the bare object model, collapsing')
            return False, None, None
        warn(f'output "{raw_output}" on "{obj_id}.{op_id}" — resolved via name resolution to a distinct type')
        return True, graph.model_ref_for(target["identifier"]), None

    warn(f'unparsed output string "{raw_output}" on "{obj_id}.{op_id}"')
    return True, "unknown", f'// TODO: unparsed input/output string "{raw_output}"\n'


def emit_operation(obj, op, graph):
    obj_id = obj["identifier"]
    op_id = op["identifier"]
    folder = _folder_for(obj)
    base_path = f"{folder}/{kebab(obj_id)}/{kebab(op_id)}"

    input_fields = resolve_operation_input_fields(obj, op, graph)
    param_fields = params_field_defs(op, graph, obj_id, op_id)

    input_body = (
        f"namespace rpp.gen {{\n"
        f"  namespace {obj_id} {{\n"
        f"    namespace {op_id} {{\n"
        f"      model input {{\n"
        f"{indent_block(input_fields + param_fields, 4)}"
        f"      }}\n"
        f"    }}\n"
        f"  }}\n"
        f"}}\n"
    )
    write_tsp(f"{base_path}/input.tsp", input_body)

    is_distinct, type_expr, field_block = resolve_operation_output(obj, op, graph)
    if is_distinct:
        if field_block is not None:
            output_body = (
                f"namespace rpp.gen {{\n"
                f"  namespace {obj_id} {{\n"
                f"    namespace {op_id} {{\n"
                f"      model output {{\n"
                f"{indent_block(field_block, 4)}"
                f"      }}\n"
                f"    }}\n"
                f"  }}\n"
                f"}}\n"
            )
        else:
            output_body = (
                f"namespace rpp.gen {{\n"
                f"  namespace {obj_id} {{\n"
                f"    namespace {op_id} {{\n"
                f"      alias output = {type_expr};\n"
                f"    }}\n"
                f"  }}\n"
                f"}}\n"
            )
        write_tsp(f"{base_path}/output.tsp", output_body)


# ---------------------------------------------------------------------------
# Static building-block files: common scalars, associations, external placeholders
# ---------------------------------------------------------------------------


def emit_common_scalars():
    write_tsp(
        "common/identifier.tsp",
        "namespace rpp.gen.common {\n  scalar Identifier extends string;\n}\n",
    )
    write_tsp(
        "common/client-identifier.tsp",
        "namespace rpp.gen.common {\n  scalar ClientIdentifier extends string;\n}\n",
    )
    write_tsp(
        "common/phone-number.tsp",
        "namespace rpp.gen.common {\n  scalar PhoneNumber extends string;\n}\n",
    )


def emit_associations():
    write_tsp(
        "associations/aggregation.tsp",
        "namespace rpp.gen {\n  model Aggregation<T> {\n    item: T;\n  }\n}\n",
    )
    write_tsp(
        "associations/composition.tsp",
        "namespace rpp.gen {\n  model Composition<T> {\n    item: T;\n  }\n}\n",
    )
    write_tsp(
        "associations/labelled-aggregation.tsp",
        "namespace rpp.gen {\n  model LabelledAggregation<T> {\n    label: string;\n    item: T;\n  }\n}\n",
    )
    write_tsp(
        "associations/dictionary-aggregation.tsp",
        "namespace rpp.gen {\n  model DictionaryAggregation<T> is Record<T>;\n}\n",
    )
    write_tsp(
        "associations/labelled-composition.tsp",
        "namespace rpp.gen {\n  model LabelledComposition<T> {\n    label: string;\n    item: T;\n  }\n}\n",
    )
    write_tsp(
        "associations/dictionary-composition.tsp",
        "namespace rpp.gen {\n  model DictionaryComposition<T> is Record<T>;\n}\n",
    )


def emit_external_placeholders():
    for (spec, type_name), ident in _external_types_seen.items():
        file_slug = kebab(spec.replace("-", "")) if False else spec.lower().replace("_", "-")
        write_tsp(
            f"external/{file_slug}-{type_name.lower()}.tsp",
            f"namespace rpp.gen.external {{\n"
            f"  // TODO: opaque placeholder for External:{spec}:{type_name} — real modelling out of scope\n"
            f"  model {ident} {{}}\n"
            f"}}\n",
        )


# ---------------------------------------------------------------------------
# main.tsp
# ---------------------------------------------------------------------------


def emit_main():
    lines = [f'import "./{path}";' for path in _written_files]
    body = "\n".join(lines) + "\n"
    (OUT_DIR / "main.tsp").write_text(HEADER + body)
    _written_files.append("main.tsp")  # for completeness, though main.tsp doesn't import itself


def emit_test_entrypoint():
    path = REPO_ROOT / "test-auto-models.tsp"
    path.write_text('import "./models-auto/main.tsp";\n')


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main():
    doc = yaml.safe_load(SPEC_YAML.read_text())
    graph = ObjectGraph(doc)

    # Pre-scan external types referenced anywhere so files can be emitted up front,
    # in dependency order (external types have no dependencies of their own).
    def prescan_data_type(dt):
        m = re.match(r"^External:([^:]+):(.+)$", dt.strip())
        if m:
            external_type_name(m.group(1), m.group(2))

    for obj in graph.components + graph.processes + graph.resources:
        for el in obj["elements"]:
            prescan_data_type(el["data_type"])
        for op in obj.get("operations", []):
            for p in op.get("params", []):
                prescan_data_type(p["data_type"])

    emit_common_scalars()
    emit_associations()
    emit_external_placeholders()

    for obj in graph.components:
        emit_component(obj, graph)

    for obj in graph.processes + graph.resources:
        emit_object_model(obj, graph)
        emit_reference(obj, graph)
        for op in obj.get("operations", []):
            emit_operation(obj, op, graph)

    emit_main()
    emit_test_entrypoint()

    warn_summary()
    print(f"Wrote {len(_written_files)} files under {OUT_DIR.relative_to(REPO_ROOT)}/", file=sys.stderr)


if __name__ == "__main__":
    main()
